name: Sync Fork

on:
  schedule:
    - cron: '1 8 * * 1' # every 30 minutes
  workflow_dispatch: # on button click
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          owner: coolsnowwolf # fork 的上游仓库 user
          head: master # fork 的上游仓库 branch
          base: master # 本地仓库 branch
